### ISSUE TITLE
Re-do Landing Page

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#125]
At present the landing page of the `imgup` app is: 
<img width="1090" alt="image" src="https://github.com/dwyl/imgup/assets/194400/dfbbaa26-81be-4c1f-9d0b-0cbb43b21478">

Please try to remember:

# _Nobody_ Cares What Tech You're Using! 

Yes, as an `engineer` you might care.
But the `person` _using_ the App doesn't care for a _millisecond_. 
You're just _wasting_ their time with this noise. 

The /liveview route: https://imgup.fly.dev/liveview is closer to what we want:
<img width="1120" alt="image" src="https://github.com/dwyl/imgup/assets/194400/96a60990-54ff-46e2-899c-66232cf4542b">

But it's still cluttered and not mobile-first/focussed:
<img width="612" alt="image" src="https://github.com/dwyl/imgup/assets/194400/d87d8ac8-7abd-4cb2-8958-09afd692faf9">

The name of the file I want to upload is below the fold, i.e. I have to scroll to see it.

<img width="612" alt="image" src="https://github.com/dwyl/imgup/assets/194400/79f86a02-5af1-4492-b347-6bf99393e322">

And there's a pointless `Upload` button that adds friction/steps to the process.
Uploading should be automatic.

# Todo

+ [ ] Remove the option for multiple ways to upload and just 
+ [ ] Show a single upload landing page with an upload interface
+ [ ] Remove the "Upload" button
+ [ ] Automatically trigger upload and display thumbnail when the image is selected or dragged in.

**Comment by nelsonic** [comment]
We _appear_ to be using this `Flowbite` (`TailwindCSS`) template:
https://flowbite.com/docs/forms/file-input/
<img width="1251" alt="image" src="https://github.com/dwyl/imgup/assets/194400/0735a5d7-f051-42ac-aaf7-ac9c58281e4c">
`if not` it's certainly _very_ similar. 💭 
`if` we borrow code, we should credit it with a comment. 💬
