### ISSUE TITLE
Chore: @dependabot Builds Fail 😢 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#151]
at present all @dependabot builds fail e.g: https://github.com/dwyl/imgup/pull/150

<img width="1471" alt="image" src="https://github.com/dwyl/imgup/assets/194400/0e2f7308-cef7-4c6a-9e99-0facadeb34a8">

https://github.com/dwyl/imgup/actions/runs/6767687337/job/18390719882#step:7:211
<img width="1499" alt="image" src="https://github.com/dwyl/imgup/assets/194400/e79f1311-b8bb-4b31-bc8a-a4f5aeb801ee">

The explanation is fairly simple: @dependabot doesn't have access to the AWS Keys so cannot upload. 🙃 

# Todo

+ [ ] document the absolute minimum permissions set required to make this work.
+ [ ] ***either*** create a separate low-risk AWS account and grant @dependabot access 
+ [ ] ***OR*** create a new `user` (AMI) on our main account with the minimum priviledges and grant access to that. 

@LuchoTurtle can you help with this or does it need to be me? 💭 
e.g: do you have your _own_ AWS account and can deploy the app to check the permissions? 🔐 

Applied `priority-1` to this because it bugs me and _should_ be straightforward to figure out. 
`T1h` is my _estimate_ of how long it should take to check the permissions, document them and create a user for @dependabot.
Please feel free to apply a different time estimate label if you get stuck. As always, lots of comments. 🙏

**Comment by LuchoTurtle** [comment]
I'd try but I need to reset the password to have access to the account.

<img width="1086" alt="image" src="https://github.com/dwyl/imgup/assets/17494745/121223f2-0de8-44f7-bcb4-d3e66c3e0dab">

Unfortunately, I'm not able to reset my password without root's permission. :/

![Screenshot 2023-11-06 at 09 40 06](https://github.com/dwyl/imgup/assets/17494745/a2d85dae-3149-45b6-9d65-271d7ef32013)

**Comment by nelsonic** [comment]
@LuchoTurtle I have manually set your AWS user to reset the password. you should be able to reset it and sign-in.
But while I'm here, I'm just going to create an account for @dependabot and see if I can get this all done _now_. 🤞

**Comment by nelsonic** [comment]
Created a user `dependabot-github-actions` on AWS (staging) that has _minimal_ permissions (only upload to `S3`):
https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/users/details/dependabot-github-actions?section=permissions
<img width="1049" alt="image" src="https://github.com/dwyl/imgup/assets/194400/cb25c08c-7166-471a-acdd-ef418d51b0e7">

@LuchoTurtle you should be able to see it as you have `IAMFullAccess`. 💭 

Created an access key and added it to the secrets of this project:
https://github.com/dwyl/imgup/settings/secrets/dependabot

<img width="1045" alt="image" src="https://github.com/dwyl/imgup/assets/194400/0e96b7ee-ef20-48c0-b335-2c45229a8fc1">

Re-ran the build: https://github.com/dwyl/imgup/actions/runs/6767687337 appears to pass:
<img width="1274" alt="image" src="https://github.com/dwyl/imgup/assets/194400/fe2d2e22-627b-4982-b8d9-cdac6694e24a">

But I don't know if this is because I triggered the build. 💭 

Going to merge one of the @dependabot PRs and see if it passes on `main`.

**Comment by LuchoTurtle** [comment]
I can see it.

![image](https://github.com/dwyl/imgup/assets/17494745/0276cd76-2c2c-4399-9153-e0759ed4cdae)

And the builds are apparently working now, as well. I'll leave it up to you to close this issue 👌

**Comment by nelsonic** [comment]
Thanks for confirming. ✅ 
Builds are passing. 🎉 
Closing. 📕
