### ISSUE TITLE
Feat: Image Upload API

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#53]
Once we have the _basic_ Web-based image uploading working there are _many_ enhancements we can make. ✨ 
Hopefully by making _everything_ Open Source - as always - we invite contributions from the community. 🤞 
However from _our_ perspective @dwyl what we want is the ability to upload from our `Flutter` (`Native` Mobile) App. 

# Todo

+ [ ] Create a **_Secure_ REST API endpoint** that allows a client e.g. `JS` or `Flutter` to upload an image
+ [x] Ideally should be streaming to provide visual feedback of the upload progress
+ [x] Should return the URL of the image once uploaded

> **Note**: this issue is not complete. It's a place-holder for the discussion around features/requirements. 
Once we have #51 working in the Web interface, this is the next logical step.

**Comment by LuchoTurtle** [comment]
It's interesting that a person had a similar idea two weeks ago -> https://elixirforum.com/t/suggestions-for-image-upload-in-json-api/56042.

**Comment by LuchoTurtle** [comment]
We should start with accepting `multipart/form-data` files, validating them through the `:API` pipeline/scope and upload to `S3`.
The process to upload the files to `S3` buckets will probably different, as the other is made through the Javascript client. Because we're doing an API-oriented approach, I think it makes sense to make use of a package like https://github.com/ex-aws/ex_aws_s3 to upload the files to S3 and return the `url` to the person/client consuming the API.

**Comment by nelsonic** [comment]
Yeah, this is definitely not a "new" idea. 
Glad someone `else` is asking useful questions.
Though I _highly_ doubt their eventual implementation will be Open Source ...
The direct upload to S3 is fine in `JS-land` but does it work in `Flutter`? 🤷‍♂️ 

This recent tutorial in `Flutter` uses a `Node.js` (`Express`) server as an `HTTP` proxy for uploading to `S3`: https://medium.com/swlh/uploading-images-to-s3-flutter-part-1-92c52ce62432 (⚠️ Warning: contains lots of `GIFs` ...)

Definitely use the `ex_aws_s3` to do the heavy lifting. 👌

**Comment by LuchoTurtle** [comment]
I keep getting this error: 

```
You tried to access the AWS EC2 instance meta, but it could not be reached.
This happens most often when trying to access it from your local computer,
which happens when environment variables are not set correctly prompting
ExAws to fallback to the Instance Meta.

Please check your key config and make sure they're configured correctly:

For Example:
```
ExAws.Config.new(:s3)
ExAws.Config.new(:dynamodb)
```
```

Even though I have set the configuration in `config.ex` :/ 

```elixir
config :ex_aws,
  access_key_id: [{:system, System.fetch_env!("AWS_ACCESS_KEY_ID")}, :instance_role],
  secret_access_key: [{:system, System.fetch_env!("AWS_SECRET_ACCESS_KEY")}, :instance_role]

```

**Comment by LuchoTurtle** [comment]
As discussed, the problem was in the `upload` function in 

```elixir
    
	image.path
      |> ExAws.S3.Upload.stream_file()
      |> ExAws.S3.upload("imgup-original", image.filename)
      |> ExAws.request!
```

There wasn't a filename prior (the documentation makes it seem that it's just the path, not the filename).

**Comment by nelsonic** [comment]
Glad you figured it out. 👌

**Comment by nelsonic** [comment]
As @LuchoTurtle noted on standup this morning, 
the `lib/app_web/components/core_components.ex` file 
is currently being ignored in the [`coveralls.json#L10-L11`](https://github.com/dwyl/imgup/blame/eacf8543259403f4fd2f92e6b5ad50eca602e368/coveralls.json#L10-L11) file:

https://github.com/dwyl/imgup/blob/eacf8543259403f4fd2f92e6b5ad50eca602e368/coveralls.json#L10-L11

That means that the [`api_test.exs`](https://github.com/dwyl/imgup/blob/api-%2353/test/app_web/api_test.exs) are incomplete.

**Comment by nelsonic** [comment]
Getting the following error when attempting to test this:

```sh
1) test upload succeeds (AppWeb.APITest)
     test/app_web/api_test.exs:18
     ** (ArgumentError) no "400" json template defined for AppWeb.ErrorJSON
     code: conn = post(conn, ~p"/api/images", @create_attrs)
     stacktrace:
       (phoenix_template 1.0.1) lib/phoenix/template.ex:241: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.1) lib/phoenix/template.ex:126: Phoenix.Template.render_to_iodata/4
       (phoenix 1.7.3) lib/phoenix/controller.ex:1008: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
       (telemetry 1.2.1) /Users/n/code/img/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
       (phoenix 1.7.3) lib/phoenix/controller.ex:974: Phoenix.Controller.render_and_send/4
       (phoenix 1.7.3) lib/phoenix/endpoint/render_errors.ex:86: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
       (phoenix 1.7.3) lib/phoenix/endpoint/render_errors.ex:63: Phoenix.Endpoint.RenderErrors.__catch__/5
       (phoenix 1.7.3) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/app_web/api_test.exs:20: (test)


Finished in 0.05 seconds (0.00s async, 0.05s sync)
2 tests, 1 failure, 1 excluded
```

**Comment by nelsonic** [comment]
Tests passing. But coverage nowhere near 100% as noted above https://github.com/dwyl/imgup/issues/53#issuecomment-1589499037

```sh
Finished in 1.4 seconds (0.00s async, 1.4s sync)
9 tests, 0 failures

Randomized with seed 324385
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% lib/app.ex                                      9        0        0
100.0% lib/app/repo.ex                                 5        0        0
100.0% lib/app/upload.ex                              64        7        0
100.0% lib/app_web/components/layouts.ex               5        0        0
 62.5% lib/app_web/controllers/api_controller.e       32        8        3
 75.0% lib/app_web/controllers/api_json.ex            24        4        1
100.0% lib/app_web/controllers/page_controller.        9        1        0
100.0% lib/app_web/controllers/page_html.ex            5        0        0
100.0% lib/app_web/endpoint.ex                        48        0        0
100.0% lib/app_web/live/imgup_live.ex                 96       27        0
100.0% lib/app_web/router.ex                          30        4        0
100.0% lib/app_web/s3_upload.ex                      127       24        0
[TOTAL]  94.7%
----------------
Generating report...
Saved to: cover/
FAILED: Expected minimum coverage of 100%, got 94.7%.
```

**Comment by nelsonic** [comment]
Sample screenshot for docs:
<img width="1134" alt="imgup-hoppscotch-api-upload" src="https://github.com/dwyl/imgup/assets/194400/c6d529bf-effd-40b4-9a5d-e5760c199344">

**Comment by nelsonic** [comment]
Of the original requirements the only one that is not met is "Secure" ... right now the API is fully open. 
We will fix this in due course. ⏳
