### ISSUE TITLE
Chore: Compressed landscape (aspect) images add black border

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#66]
At present the compressed images work fine until we have a wider image ...
https://jsfiddle.net/6t7p0eqc/7/

<img width="2330" alt="dwyl-imgup-compressed-images-add-black-border" src="https://github.com/dwyl/imgup/assets/194400/c00302c2-7401-4dbe-8b6a-741cd7ce5929">

<h1>
Original
</h1>

![image](https://github.com/dwyl/imgup/assets/194400/107acbb2-cfc9-4e26-97d7-5983b1395cd0)

<h1>
Compressed:
</h1>

![image](https://github.com/dwyl/imgup/assets/194400/8dd68e3e-2cc0-463e-a506-25d1e1941bd9)

# Todo

+ [x] Document the setup of the image compressor in https://github.com/dwyl/imgup/tree/main/an_aws_sam_imgup-compressor adding _all_ the steps taken to deploy the app on `AWS`: https://github.com/dwyl/imgup#7-resizingcompressing-files
+ [x] Alter the `.resize` code that currently creates a `200x200` square:

https://github.com/dwyl/imgup/blob/a6596c6e2289d03d7b50d73b998db405fd9086ed/an_aws_sam_imgup-compressor/src/index.js#L20-L24

  + [x] Should only constrain in one dimension e.g: _only_ `width` or _only_ `height` 
  i.e. preserve the aspect ratio of images.

+ [x] Redeploy the `compressor` app on `AWS`. 
+ [x] Confirm that compressed images are preserving aspect ratio (not adding black border)

**Comment by nelsonic** [comment]
Related to #72 💔 
Could be worth doing both these updates at the same time. 💭
