### ISSUE TITLE
Feat: Logging + Metrics

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#89]
# This is "on hold" ... pending https://github.com/dwyl/logs/issues/1

At present the **`imgup` app** has **no `DB`** 💭  
***So*** we have _zero_ insight into what images are being uploaded. 🙈 🤷‍♂️ 
This is "OK" for a basic demo... :shipit: 
But it's not great for a "production" app where we want to track metrics. 📈 
We need to "[productionize](https://en.wiktionary.org/wiki/productionize)"! 🚀 

# Todo

+ [ ] **Define** the **`DB` schema** for storing _anon_ logging data. 
We can borrow (or draw inspiration) from: [`dwyl/auth/lib/auth/log.ex`](https://github.com/dwyl/auth/blob/83c286a24d47bd087ba41925a740d4030cf95e19/lib/auth/log.ex#L11-L21) 
  + [ ] `user_agent` table should mimmic the one in `auth`: [`lib/auth/user_agent.ex`](https://github.com/dwyl/auth/blob/83c286a24d47bd087ba41925a740d4030cf95e19/lib/auth/user_agent.ex) so that we store the relevant detail. The other field we could add is 
+ [ ] Create the necessary `migrations` for the schema we define.
+ [ ] Create a simple interface that logs required events ...
